---

# Example sandbox configuration
# for single server community
# installs


- name: Deploy edxapp
  hosts: 
  sudo: True
  gather_facts: True
  roles:
    - aws
    - role: nginx
      nginx_sites:
      - lms
      - cms
      nginx_default_sites:
      - lms
    - edxapp